### ISSUE TITLE
Not installing properly on linux

### ISSUE THREAD

**Issue by stevexyz** [jacobly0/fasmg-ez80#12]
After cloning tried installing fasmg with provided script but obtained:
```
$ ./install_fasmg 
+ case "$TRAVIS_OS_NAME" in
+ echo 'Unknown OS: '
Unknown OS: 
+ exit 1
```

After modifying script to work in linux setting the variable TRAVIS_OS_NAME got:
```
[...omnissis...]
./install_fasmg: line 12: fasmg.patch: No such file or directory
```

After pointing to patch file (in ..) got:
```
[...omnissis...]
+ patch -p0 -d fasmg
patching file docs/manual.txt
patching file source/reader.inc
patching file source/version.inc
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file source/version.inc.rej
```

Removing the patching of version file managed to get the new fasmg recompiled.

Willing to point out the issue to hopefully know if I'm doing something wrong and what is the reason to patch fasmg afterwards instead of integrating in the upstream...

**Comment by jacobly0** [comment]
That script is meant to be run from other places to create a patched fasmg for assembling the output of certain C compilers, and stops working every time upstream fasmg is updated.  If you just want fasmg you can simply download it from the website.  If you do want the patched one for some reason, you can run `TRAVIS_OS_NAME=linux bin/install_fasmg`.
