### ISSUE TITLE
How is this supposed to be used?

### ISSUE THREAD

**Issue by Xeraster** [jacobly0/fasmg-ez80#18]
Could someone explain how I'm supposed to use this to assemble code for the ez80? The only clue is the fasmg download in the readme. Once downloading that as well, there doesn't seem to be any way to "install" this as an addon or into the source code that I can figure out.

I did find a file called "install_fasmg" in the bin folder. Running that gives me the error "Error: failed to write the output file". Running the fasm executable does work but it can't assemble any z80 or ez80 code.

What steps need to be taken to get this set up as a working ez80 assembler?

**Comment by jacobly0** [comment]
If you just want to assemble ez80 instructions all you need is `include '../fasmg-ez80/ez80.inc'` or similar at the top of the file and then run `path/to/fasmg input.asm output.bin`.
