### ISSUE TITLE
jq is broken

### ISSUE THREAD

**Issue by mateoconlechuga** [jacobly0/fasmg-ez80#19]
This toolchain project: [tanks-ce.zip](https://github.com/jacobly0/fasmg-ez80/files/8721912/tanks-ce.zip) fails to link because `jq` seems to be struggling. Changing the `jq` to `jp` in lto.src allows the linking to succeed.

**Comment by mateoconlechuga** [comment]
> 20:26 <•jacobly> it's an infinite loop
20:26 <•jacobly> duh

**Comment by jacobly0** [comment]
The compiler no longer emits jq.

**Comment by mateoconlechuga** [comment]
that just seems like cheating :)
