### ISSUE TITLE
show all unresolved symbols at link time

### ISSUE THREAD

**Issue by parisseb** [jacobly0/fasmg-ez80#20]
Is it possible to display all unresolved symbols at link time? I expect to have a few hundreds one when trying to link KhiCAS for the first time. Since linking will probably take a couple of minutes or more, it would be awesome to have more than 1 unresolved symbol each time I link!

**Comment by jacobly0** [comment]
`    -e limit    Set the maximum number of displayed errors (default 1)`

Using the ez80 toolchain it would be something like `make EXTRA_LDFLAGS="-e 9999"`.
