### ISSUE TITLE
fasmg breaks when relocation address is inside relocated block

### ISSUE THREAD

**Issue by mateoconlechuga** [jacobly0/fasmg-ez80#4]
So I am writing an program using app.inc (buildable [here](https://github.com/mateoconlechuga/cesium/tree/feature/cesium-rewrite) on branch `feature/cesium-rewrite` with `fasmg src/cesium.asm cesium.8xp`), and there appears to be an issue with relocated blocks.

I have pushed this snippet of code to replicate:

https://github.com/mateoconlechuga/cesium/blob/38a44a52d85e70592986408a5cf34a2528c8c716/src/cesium.asm#L16-L20

```asm
    relocate bad_fasmg, $d00000
        call    bad_label
    end relocate

    bad_label:
```
It seems I cannot call a routine that exists in relocated flash from a different relocated block. Any help would be much appreciated :)

The error given is shown below:
![image](https://user-images.githubusercontent.com/9890252/42140227-946b143a-7d59-11e8-8c9f-8d23e176aaaf.png)

**Comment by jacobly0** [comment]
Fixed in the external relocate macro.
